"use client";
import { Provider, useSelector } from "react-redux";
import "./globals.css";
import { Inter } from "next/font/google";
import { store } from "@/store";
import WithAuth from "@/hocs/withAuth.hoc";
import App from "@/components/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Facegen Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
            <WithAuth><App>{children}</App></WithAuth>
        </Provider>
      </body>
    </html>
  );
}
function dispatch(arg0: any) {
  throw new Error("Function not implemented.");
}

